version: '3.7'

services:
  docker-network-exposer:
    build: .
    init: true
    stop_signal: SIGINT
    stop_grace_period: 1m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/etc/dnsmasq.d/addn-hosts:/opt/docker-network-hosts/addn-hosts
      - ./config:/etc/openvpn/client-config
    cap_add:
      - NET_ADMIN
    ports:
      - '1194:1194'

  nginx:
    image: nginx
