version: "3"

services:
    docker-network-exposer:
        build: .
        volumes:
            - ./config:/etc/openvpn/
        cap_add:
            - NET_ADMIN
        ports:
            - "1194:1194"

    nginx:
        image: nginx
